// <auto-generated />
namespace Swapps_Web_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TimeIntervalNullability : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TimeIntervalNullability));
        
        string IMigrationMetadata.Id
        {
            get { return "201812142213512_TimeIntervalNullability"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
