// <auto-generated />
namespace Swapps_Web_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EstablishmentRequiredChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EstablishmentRequiredChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201812121256556_EstablishmentRequiredChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
